# Generated by Django 5.1.4 on 2026-09-15 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المقدم')),
                ('date_received', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الاستلام')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات (اختياري)')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='الصنف / الطلب')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('date_requested', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تم الحساب؟')),
            ],
        ),
    ]
