# Generated by Django 5.1.4 on 2026-09-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='تم تصفير الحساب؟'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات'),
        ),
    ]
